### ISSUE TITLE
header.tex does not compile in Overleaf V2

### ISSUE THREAD

**Issue by rtanamachi** [jeremygibbs/nsf-proposal-latex#1]
Output of error log:

> Emergency stop.
> 
> <*> header.tex
>               
> *** (job aborted, no legal \end found)
> 
>  
> Here is how much of TeX's memory you used:
>  8866 strings out of 492990
>  129041 string characters out of 6132621
>  224977 words of memory out of 5000000
>  12339 multiletter control sequences out of 15000+600000
>  4709 words of font info for 16 fonts, out of 8000000 for 9000
>  1141 hyphenation exceptions out of 8191
>  36i,0n,45p,223b,37s stack positions out of 5000i,500n,10000p,200000b,80000s
> !  ==> Fatal error occurred, no output PDF file produced!

**Comment by johnrobertlawson** [comment]
I had the same issue, but (a) I noticed Overleaf hadn't set my "main document" as main.tex, and (b) I tried the compile button numerous times. It then compiled successfully but the site then crashed. Ha. Jeremy?...

**Comment by jeremygibbs** [comment]
Robin, I am sorry for never responding to this. I must have missed the notification. Did John's suggestion fix this?

**Comment by rtanamachi** [comment]
Hi Jeremy, Thanks for responding. I've set the main document to be "main.tex", and while it compiles, trying to compile "header.tex" separately still doesn't work. IT doesn't seem to be holding me back from compiling main.tex, though.
