### ISSUE TITLE
Could not generate PDF if there is math symbols in the tex

### ISSUE THREAD

**Issue by Bing2022** [jeremygibbs/nsf-proposal-latex#3]
Hello,

Thank you so much for providing such a beautiful latex template for the NSF funding. I downloaded it and try to compile it. 

Once I have math equation in any file, like $\tau$, or $\mathbb{R}$, the compile will fail. But $abc$ works. I checked packages, \usepackage{amsmath, amsthm, amssymb} is included in the header file. 

The error message it shows is "Sorry, but miktex-makemf did not succeed. The log file hopefully contains the information to get MiKTeX going again: C:\Users\bm1238\AppData\Local\MiKTeX\miktex\log\miktex-makemf.log"

The log is empty.

My Mitex works well for other template with math equations, like \documentclass[letterpaper, 10 pt, conference]{ieeeconf}

I appreciate your help so much!

Best,

Bing

**Comment by jeremygibbs** [comment]
I am sorry for not seeing this sooner. Is this still an error you are encountering?
